checks:
  php:
    code_rating: true
    duplication: true


filter:
  paths:
    - src/*

before_commands:
  - "composer install"

tools:
  php_code_sniffer:
    config:
      standard: "PSR12"
  php_cs_fixer: true
  sensiolabs_security_checker: true
