dist: bionic
language: php

matrix:
  include:
    - php: 7.3
    - php: 7.4
    - php: 8.0

  allow_failures:
    - php: 8.0

branches:
  only:
    - master

install:
  - composer install

script:
  - composer test-clover

after_success:
  - composer coveralls
